name: Build SimpleOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Explicitly specify ubuntu-24.04 instead of latest
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y debootstrap

    - name: Build SimpleOS
      run: |
        chmod +x build.sh
        sudo ./build.sh

    - name: Upload distribution archive
      uses: actions/upload-artifact@v4  
      with:
        name: simpleos-distribution
        path: dist/simpleos-*.tar.gz
        retention-days: 90  # Optional: specify how long to keep the artifact